"""empty message

Revision ID: 58342fae5487
Revises: 79101645ee4e
Create Date: 2021-02-03 11:35:25.713592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58342fae5487'
down_revision = '79101645ee4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
